Updated the deployment script for proper testing

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -6,7 +6,54 @@ on:
       - main
 
 jobs:
-  clean:
+  test-new-build:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v2
+
+      - name: Install SSH Client and sshpass
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y openssh-client sshpass
+          sudo apt-get install -y python3-pip
+
+
+      - name: SSH into Google Cloud VM for testing
+        run: |
+          set -e 
+          sshpass -p ${{ secrets.TESTER_SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.TESTER_SSH_USERNAME }} << EOF
+            echo "Current directory path: $(pwd)"
+            cd 
+            rm -rf Epoch
+            sudo fuser -k -n tcp 443
+            sudo fuser -k -n tcp 8080
+            sudo fuser -k -n tcp 80
+            sudo fuser -k -n tcp 8000
+            docker stop \$(docker ps -q)
+            docker rm \$(docker ps -aq)
+            docker rmi \$(docker images -q)
+            git clone https://github.com/Aymanhki/Epoch.git 
+            cd
+            cd Epoch/epoch_backend/assets/
+            cp /etc/letsencrypt/live/aymanhkias.com/fullchain.pem ./
+            cp /etc/letsencrypt/live/aymanhkias.com/privkey.pem ./
+            cd
+            cd Epoch/epoch_frontend/
+            cp /etc/letsencrypt/live/aymanhkias.com/fullchain.pem ./
+            cp /etc/letsencrypt/live/aymanhkias.com/privkey.pem ./
+            cd
+            cd Epoch/
+            if ! pytest --cov=epoch_backend -rA -vv --color=yes ./epoch_backend/tests/webserver_tests.py; then
+              echo "Test(s) failed. Exiting with status 1."
+              exit 1
+            fi
+            exit 0
+          EOF
+
+  clean-old-build:
+    needs: test-new-build
     runs-on: ubuntu-latest
 
     steps:
@@ -44,37 +91,8 @@ jobs:
             exit
           EOF
 
-  test:
-    needs: clean
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v2
-
-      - name: Install SSH Client and sshpass
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y openssh-client sshpass
-          sudo apt-get install -y python3-pip
-          
-
-      - name: SSH into Google Cloud VM for testing
-        run: |
-          set -e 
-          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }} << EOF
-            echo "Current directory path: $(pwd)"
-            cd
-            cd Epoch/
-            if ! pytest --cov=epoch_backend -rA -vv --color=yes ./epoch_backend/tests/webserver_tests.py; then
-              echo "Test(s) failed. Exiting with status 1."
-              exit 1
-            fi
-            exit 0
-          EOF
-
-  deploy:
-    needs: test
+  deploy-new-build:
+    needs: clean-old-build
     runs-on: ubuntu-latest
 
     steps:
