Added some frontend tests to the CI-CD Pipeline

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -41,6 +41,12 @@ jobs:
               echo "Test(s) failed. Exiting with status 1."
               exit 1
             fi
+            cd epoch_frontend/
+            if ! npm test; then
+              echo "Test(s) failed. Exiting with status 1."
+              exit 1
+            fi
+            cd ..
             if ! docker build -t epoch_backend ./epoch_backend/; then
               echo "Docker build failed. Exiting with status 1."
               exit 1
