Deployment test (SHOULD FAIL)

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -60,6 +60,7 @@ jobs:
 
       - name: SSH into Google Cloud VM for testing
         run: |
+          set -e 
           sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }} << EOF
             echo "Current directory path: $(pwd)"
             cd
@@ -67,10 +68,12 @@ jobs:
             nohup python3 main.py > main.log 2>&1 &
             pip install -r requirements.txt
             pip install pytest
-            python3 -m pytest -rA -vv --color=yes tests/webserver_tests.py
-            EXIT_STATUS=$?
+            if ! python3 -m pytest -rA -vv --color=yes tests/webserver_tests.py; then
+              echo "Test(s) failed. Exiting with status 1."
+              exit 1
+            fi
             pkill -f "python3 main.py"
-            exit $EXIT_STATUS
+            exit 0
           EOF
 
   deploy:
